$(document).ready(function() {
    $("#chapati").click(function(){
      $("#chapati-showing").toggle("slow");
      $(".hide-chapati-image").toggle();
    })
    $("#fries").click(function(){
      $("#fries-showing").toggle("slow");
      $(".hide-fries-image").toggle();
    })
    $("#chicken").click(function(){
      $("#chicken-showing").toggle("slow");
      $(".hide-chicken").toggle();
    })
  // SECTION 2
    $("#curry").click(function(){
    $("#curry-showing").toggle("slow");
    $(".hide-curry-image").toggle();
    })
    $("#pilau").click(function(){
    $("#pilau-showing").toggle("slow");
    $(".hide-pilau-image").toggle();
    })
    $("#salmon").click(function(){
    $("#salmon-showing").toggle("slow");
    $(".hide-salmon-image").toggle();
    })
  // SECTION 3
  $("#burger").click(function(){
  $("#burger-showing").toggle("slow");
  $(".hide-burger-image").toggle();
  })
  $("#pasta").click(function(){
  $("#pasta-showing").toggle("slow");
  $(".hide-pasta-image").toggle();
  })
  $("#spag").click(function(){
  $("#spag-showing").toggle("slow");
  $(".hide-spag-image").toggle();
  })
  });