$(document).ready(function() {
    $("#chapati").click(function(){
      $("#chapati-showing").toggle("slow");
      $(".hide-chapati-image").toggle();
    })
    $("#fries").click(function(){
      $("#fries-showing").toggle("slow");
      $(".hide-fries-image").toggle();
    })
    $("#chicken").click(function(){
      $("#chicken-showing").toggle("slow");
      $(".hide-chicken").toggle();
    })
  // SECTION 2
    $("#sausage").click(function(){
    $("#sausage-showing").toggle("slow");
    $(".hide-sausage-image").toggle();
    })
    $("#waffles").click(function(){
    $("#waffles-showing").toggle("slow");
    $(".hide-waffles-image").toggle();
    })
    $("#eggs").click(function(){
    $("#eggs-showing").toggle("slow");
    $(".hide-eggs-image").toggle();
    })
  // SECTION 3
  $("#donuts").click(function(){
  $("#donuts-showing").toggle("slow");
  $(".hide-donuts-image").toggle();
  })
  $("#Potatoes").click(function(){
  $("#Potatoes-showing").toggle("slow");
  $(".hide-Potatoes-image").toggle();
  })
  $("#tea").click(function(){
  $("#tea-showing").toggle("slow");
  $(".hide-tea-image").toggle();
  })
  });